### ISSUE TITLE
Add support for HTTP2 requests in Curl

### ISSUE THREAD

**Issue by mnapoli** [brefphp/aws-lambda-layers#42]
We had that issue in Bref 1 previously:

- [issue](https://github.com/brefphp/bref/issues/727)
- [PR](https://github.com/brefphp/bref/pull/740)

We need to fix that in the new layers as well.

Here is how I checked the problem:

- Run `bash` in a Bref container
  - `docker run --rm -it --entrypoint=bash bref/php-81:1.7.15`
  - `docker run --rm -it --entrypoint=bash bref/php-81:2`
- Check `php -i | grep HTTP2` and `php -r "var_dump(get_defined_constants());" | grep CURL_HTTP`

I should see these constants:

```
  ["CURL_HTTP_VERSION_1_0"]=>
  ["CURL_HTTP_VERSION_1_1"]=>
  ["CURL_HTTP_VERSION_NONE"]=>
  ["CURL_HTTP_VERSION_2_0"]=>
  ["CURL_HTTP_VERSION_2"]=>
  ["CURL_HTTP_VERSION_2TLS"]=>
  ["CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE"]=>
```

But instead I see only these:

```
  ["CURL_HTTP_VERSION_1_0"]=>
  ["CURL_HTTP_VERSION_1_1"]=>
  ["CURL_HTTP_VERSION_NONE"]=>
```

In Bref 1, we compiled LIBNGHTTP2. In Bref 2 I'd love to find a solution that doesn't involve compiling (slow), if we can install a package that's better.

@shouze do you have any idea?

**Comment by mnapoli** [comment]
What is weird is that libnghttp2 is already installed in AL2…

```
ldd /lib64/php/modules/curl.so
	libcurl.so.4 => /lib64/libcurl.so.4 (0x0000004001a45000)
	libc.so.6 => /lib64/libc.so.6 (0x0000004001cdc000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x0000004002089000)
	...
```

And `/lib64/libnghttp2.so.14` is already here in AL2. We can even try to install it:

```
yum install libnghttp2

...

Package libnghttp2-1.41.0-1.amzn2.x86_64 already installed and latest version
```

So I'm not sure what's missing here. We don't copy `libnghttp2.so.14` in the Lambda layer because that file already exists on Lambda/in AL2.

**Comment by mnapoli** [comment]
Forgot to mention: the CURL version in the new layers is `7.79.1`, so it should be more than enough to have the HTTP 2 constants. Something is missing but I'm not sure what.

**Comment by shouze** [comment]
> So I'm not sure what's missing here. We don't copy `libnghttp2.so.14` in the Lambda layer because that file already exists on Lambda/in AL2.

@mnapoli are you experiencing on x86, arm or both?
I've quickly checked and yes at least in the docker image looks like libnghttp2 is installed by default in AL2:

```fish
❯ docker run --rm -it --entrypoint= public.ecr.aws/lambda/provided:al2-x86_64 find / -iname 'libnghttp*'
/usr/lib64/libnghttp2.so.14.20.0
/usr/lib64/libnghttp2.so.14
/usr/share/licenses/libnghttp2-1.41.0
```
So... are you experiencing on the true runtime lambda layer, AL2 docker image or both? If only on rumtime lambda layer, worth to double check there's no diff between AL2 docker image & true lambda runtime layers.

Then, despite the libnghttp2 is provided, it then depends if installed libcurl has been compiled with libnghttp2 support or not. And it seems that libcurl is not provided by default in AL2 layer. And finally, it depends if php itself has been eventually compiled with libnghttp2.

And looks like... yes (at least on x86):
```fish
❯ docker run --rm -it --entrypoint=bash bref/php-81:2 ldd /opt/bref/extensions/curl.so | grep nghttp
        libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f8915550000)

```

So, maybe Remi compiles php with php support included instead of letting it as a separate extension? So even if the extension looks like to support http2, in fact this extension is unused? Looks like no, because the extension is loaded:
```fish
bash-4.2# php -m | grep curl
curl
```

I've also tried to not load the extension and then `php -i | grep -i curl` returns nothing, so not builtin php binary by default.

I have to admit, this drives me nuts!
